import React, { useState, useRef, useEffect } from 'react';
import { Menu, Info } from 'lucide-react';

const Header = ({ onMenuClick, currentBookName }) => {
  const [showAbout, setShowAbout] = useState(false);
  const aboutRef = useRef();

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (aboutRef.current && !aboutRef.current.contains(event.target)) {
        setShowAbout(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [aboutRef]);

  return (
    <header>
      <div className="title-credits">
        <div className="title-row">
          <button onClick={onMenuClick} className="icon-btn menu-btn" aria-label="Open Books Menu">
            <Menu size={24} color="var(--text-color)" />
          </button>
          <h1>Mapping the Bible {currentBookName && <span style={{opacity: 0.6, fontSize: '0.8em'}}>| {currentBookName}</span>}</h1>
        </div>
        <div className="header-actions">
          <button className="icon-btn about-btn" onClick={() => setShowAbout(!showAbout)}>
            <Info size={18} color="var(--text-color)" /> About
          </button>
          {showAbout && (
            <div className="about-modal" ref={aboutRef}>
              <h3>About this Project</h3>
              <p>
                <strong>Dataset:</strong> Built using the historic <em>Douay-Rheims Catholic Bible</em> text.
              </p>
              <p>
                <strong>Methodology:</strong> The network was generated by scanning the entire Biblical text using 
                Natural Language Processing (<strong>spaCy NER</strong>) to automatically detect and extract character names and their connections verse-by-verse.
              </p>
              <p>
                <strong>Algorithms:</strong> The visualization uses a <strong>Breadth-First Search (BFS)</strong> algorithm to isolate connected networks, and a <strong>D3 Force-Directed Physics Engine</strong> to dynamically simulate relationships (pulling connected characters together and repelling unrelated ones).
              </p>
              <p>
                <a href="https://github.com/Ignisko/Bibbia-rete/blob/main/bible-network-visualizer/docs/methodology.md" target="_blank" rel="noopener noreferrer">
                  📄 Read the full Methodology & Features Paper
                </a>
              </p>
              <hr style={{ margin: '1rem 0', borderColor: 'var(--border-color)', borderBottom: 'none' }} />
              <p style={{ fontSize: '0.85rem' }}>Inspired by <strong>Prof. Dmitry Zinoviev</strong>.</p>
              <p style={{ fontSize: '0.85rem' }}>Created by <a href="https://idiotajezusa.pl/" target="_blank" rel="noopener noreferrer">https://idiotajezusa.pl/</a></p>
            </div>
          )}
        </div>
      </div>
    </header>
  );
};

export default Header;
