import React, { useState, useRef, useEffect } from 'react';
import { Menu, Info } from 'lucide-react';

const Header = ({ onMenuClick, currentBookName }) => {
  const [showAbout, setShowAbout] = useState(false);
  const aboutRef = useRef();

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (aboutRef.current && !aboutRef.current.contains(event.target)) {
        setShowAbout(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [aboutRef]);

  return (
    <header>
      <div className="title-credits">
        <div className="title-row">
          <button onClick={onMenuClick} className="icon-btn menu-btn" aria-label="Open Books Menu">
            <Menu size={24} color="var(--text-color)" />
          </button>
          <h1>Mapping the Bible {currentBookName && <span style={{opacity: 0.6, fontSize: '0.8em'}}>| {currentBookName}</span>}</h1>
        </div>
        <div className="header-actions">
          <button className="icon-btn about-btn" onClick={() => setShowAbout(!showAbout)}>
            <Info size={18} color="var(--text-color)" /> About
          </button>
          {showAbout && (
            <div className="about-modal" ref={aboutRef}>
              <h3>About this project</h3>
              
              <p style={{ marginBottom: '1rem', fontSize: '0.95rem' }}>
                An interactive map of every character interaction in the <strong>Douay-Rheims Catholic Bible</strong>.
              </p>

              <div style={{ fontSize: '0.85rem', color: '#555' }}>
                <p><strong>How to use:</strong> Hover over any name to highlight their connections. Use the menu (top-left) to switch books.</p>
                
                <p style={{ marginBottom: '0.5rem' }}><strong>Methodology:</strong> The network was generated by scanning the Biblical text using AI (spaCy NER) to automatically extract character names verse-by-verse. A physics engine then clusters closely related characters together.</p>
                <p><strong>Validation References:</strong> Because AI extraction can generate false positives (e.g., abstract concepts flagged as names), the dataset is cross-referenced with canonical biblical character dictionaries, including:</p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '0.2rem' }}>
                  <li><a href="https://books.google.pl/books?id=aE7EyQ_HQAMC" target="_blank" rel="noopener noreferrer">The Dictionary of the Bible (John L. McKenzie)</a></li>
                  <li><a href="https://books.google.pl/books?id=pxC3EQAAQBAJ" target="_blank" rel="noopener noreferrer">All the People in the Bible (Richard R. Losch)</a></li>
                </ul>
              </div>

              <p style={{ marginTop: '1rem' }}>
                <a href="https://github.com/Ignisko/Bibbia-rete/blob/main/bible-network-visualizer/docs/methodology.md" target="_blank" rel="noopener noreferrer" style={{ fontSize: '0.9rem' }}>
                  📄 Read the full methodology paper
                </a>
              </p>
              
              <hr style={{ margin: '1rem 0', borderColor: 'var(--border-color)', borderBottom: 'none' }} />
              
              <div style={{ fontSize: '0.85rem', color: '#666', display: 'flex', justifyContent: 'space-between' }}>
                <span>Inspired by <strong>Prof. Dmitry Zinoviev</strong></span>
                <span>Created by <a href="https://idiotajezusa.pl/" target="_blank" rel="noopener noreferrer">idiotajezusa.pl</a></span>
              </div>
            </div>
          )}
        </div>
      </div>
    </header>
  );
};

export default Header;
